# Generated by Django 5.2.10 on 2026-03-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='content_am',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title_am',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
