# Generated by Django 5.2.10 on 2026-03-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_story_content_am_alter_story_title_am'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='is_approved',
        ),
    ]
